DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Gotchis;

CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE Gotchis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER,
  name TEXT NOT NULL DEFAULT 'Gotchi',
  birthdate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deathdate DATETIME,
  health INTEGER NOT NULL DEFAULT 100,
  hunger INTEGER NOT NULL DEFAULT 100,
  hunger_status TEXT NOT NULL DEFAULT 'Full',
  last_fed DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES Users(id)
);